---
# Compliance audit - each_actual_value_is_within_range #
########################################################
# ubuntu_rule_key - key of the rule
# ubuntu_baseline_key - key of the baseline being checked

- name: Compliance Audit | {{ ubuntu_baseline_key }} | Display current value of variables
  debug:
    msg: |-
      ubuntu_rule_key: {{ ubuntu_rule_key }}
      ubuntu_baseline_key: {{ ubuntu_baseline_key }}
    verbosity: 2

- name: Compliance Audit | {{ ubuntu_baseline_key }} | Set values for count variable
  set_fact:
    ubuntu_audit_match_count: 0
    ubuntu_audit_numeric_values: []

- name: Compliance Audit | {{ ubuntu_baseline_key }} | Get numeric values from actual values
  set_fact:
    ubuntu_audit_numeric_values: "{{ ubuntu_audit_numeric_values + [actual_value_item | regex_search(ubuntu_rules[ubuntu_rule_key]['expected_values'][actual_value_index][0]) | default('', true) | regex_search('[0-9]+')] }}"
  when:
    - ubuntu_rules[ubuntu_rule_key]['expected_values'][actual_value_index] is defined
    - ubuntu_rules[ubuntu_rule_key]['expected_values'][actual_value_index][0] is defined
  loop: "{{ ubuntu_rules[ubuntu_rule_key]['actual_values'] }}"
  loop_control:
    index_var: actual_value_index
    loop_var: actual_value_item

- name: Compliance Audit | {{ ubuntu_baseline_key }} | Check if each numeric value is within range
  set_fact:
    ubuntu_audit_match_count: "{{ ubuntu_audit_match_count  | default(0) | int + 1 }}"
  when:
    - ubuntu_rules[ubuntu_rule_key]['expected_values'][actual_value_index] is defined
    - ubuntu_rules[ubuntu_rule_key]['expected_values'][actual_value_index][1] is defined
    - ubuntu_rules[ubuntu_rule_key]['expected_values'][actual_value_index][1][0] is defined
    - ubuntu_rules[ubuntu_rule_key]['expected_values'][actual_value_index] is defined
    - ubuntu_rules[ubuntu_rule_key]['expected_values'][actual_value_index][1] is defined
    - ubuntu_rules[ubuntu_rule_key]['expected_values'][actual_value_index][1][1] is defined
    - numeric_value_item | length
    - numeric_value_item | int >= regex(ubuntu_rules[ubuntu_rule_key]['expected_values'][actual_value_index][1][0])
    - numeric_value_item | int <= regex(ubuntu_rules[ubuntu_rule_key]['expected_values'][actual_value_index][1][1])
  loop: "{{ ubuntu_audit_numeric_values }}"
  loop_control:
    index_var: numeric_value_index
    loop_var: numeric_value_item

- name: Compliance Audit | {{ ubuntu_baseline_key }} | Mark as compliant
  set_fact:
    ubuntu_hardening_compliance_baseline_data: "{{ ubuntu_hardening_compliance_baseline_data | combine({ubuntu_baseline_key: {'compliance': 'C' }}, recursive=true) }}"
  when: ubuntu_audit_match_count | int <= ubuntu_rules[ubuntu_rule_key]['expected_values'] | length

- name: Compliance Audit | {{ ubuntu_baseline_key }} | Display compliance
  debug:
    msg: |-
      Number of actual values and expected values matches: {{ ubuntu_audit_match_count }}
      Compliance: {{ ubuntu_hardening_compliance_baseline_data[ubuntu_baseline_key]['compliance'] }}
    verbosity: 2

- name: Risk Register Check | {{ ubuntu_baseline_key }}
  include_tasks: risk_register_check.yml
  vars:
    ubuntu_risk_register_rule_key: "{{ ubuntu_rule_key }}"
    ubuntu_risk_register_baseline_key: "{{ ubuntu_baseline_key }}"
  when:
    - ubuntu_hardening_compliance_baseline_data is defined
    - ubuntu_hardening_compliance_baseline_data[ubuntu_baseline_key]['compliance'] == 'NC'
