---
# Avoid modifying this file, and overwrite values in /vars instead

# Inventory #
#############
# Rules Value #
##################
ubuntu_cis_1_7_1_1_expected_value: ""
ubuntu_cis_1_7_1_2_expected_value: ""
ubuntu_cis_1_7_1_3_expected_value: ""
ubuntu_cis_2_2_1_2_server_expected_value: ""
ubuntu_cis_4_1_1_1_expected_value: ""
ubuntu_cis_4_1_12_partions_expected_value: ""
#ubuntu_cis_5_3_1_expected_value: ""
#ubuntu_cis_5_3_2_expected_values: []

# Rules Checking #
##################
# Enabling (true) or disabling (true) of rule checking

# CIS
ubuntu_cis_1_1_1_1: true
ubuntu_cis_1_1_1_2: true
ubuntu_cis_1_1_1_3: true
ubuntu_cis_1_1_1_4: true
ubuntu_cis_1_1_1_5: true
ubuntu_cis_1_1_1_6: true
ubuntu_cis_1_1_1_7: true
ubuntu_cis_1_1_2: false
ubuntu_cis_1_1_3: true
ubuntu_cis_1_1_4: true
ubuntu_cis_1_1_5: true
ubuntu_cis_1_1_6: false
ubuntu_cis_1_1_7: true
ubuntu_cis_1_1_8: true
ubuntu_cis_1_1_9: true
ubuntu_cis_1_1_10: false
ubuntu_cis_1_1_11: false
ubuntu_cis_1_1_12: true
ubuntu_cis_1_1_13: true
ubuntu_cis_1_1_14: true
ubuntu_cis_1_1_15: false
ubuntu_cis_1_1_16: false
ubuntu_cis_1_1_17: false
ubuntu_cis_1_1_18: true
ubuntu_cis_1_1_19: true
ubuntu_cis_1_1_20: false
ubuntu_cis_1_1_21: false
ubuntu_cis_1_1_22: true
ubuntu_cis_1_1_23: true
ubuntu_cis_1_1_24: false
ubuntu_cis_1_2_1: false
ubuntu_cis_1_2_2: false
ubuntu_cis_1_3_1: false
ubuntu_cis_1_3_2: false
ubuntu_cis_1_3_3: false
ubuntu_cis_1_4_1: false
ubuntu_cis_1_4_2: false
ubuntu_cis_1_5_1: false
ubuntu_cis_1_5_2: true
ubuntu_cis_1_5_3: true
ubuntu_cis_1_6_1: false
ubuntu_cis_1_6_2: true
ubuntu_cis_1_6_3: false
ubuntu_cis_1_6_4: true
ubuntu_cis_1_7_1_1: false
ubuntu_cis_1_7_1_2: false
ubuntu_cis_1_7_1_3: false
ubuntu_cis_1_7_1_4: false
ubuntu_cis_1_8_1_1: true
ubuntu_cis_1_8_1_2: true
ubuntu_cis_1_8_1_3: true
ubuntu_cis_1_8_1_4: true
ubuntu_cis_1_8_1_5: true
ubuntu_cis_1_8_1_6: true
ubuntu_cis_1_9: false
ubuntu_cis_1_10: true
ubuntu_cis_2_1_1: false
ubuntu_cis_2_1_2: false
ubuntu_cis_2_2_1_1: true
ubuntu_cis_2_2_1_2: false
ubuntu_cis_2_2_1_3: true
ubuntu_cis_2_2_1_4: false
ubuntu_cis_2_2_2: false
ubuntu_cis_2_2_3: false
ubuntu_cis_2_2_4: false
ubuntu_cis_2_2_5: false
ubuntu_cis_2_2_6: false
ubuntu_cis_2_2_7: false
ubuntu_cis_2_2_8: false
ubuntu_cis_2_2_9: false
ubuntu_cis_2_2_10: false
ubuntu_cis_2_2_11: false
ubuntu_cis_2_2_12: false
ubuntu_cis_2_2_13: false
ubuntu_cis_2_2_14: false
ubuntu_cis_2_2_15: false
ubuntu_cis_2_2_16: false
ubuntu_cis_2_2_17: false
ubuntu_cis_2_3_1: true
ubuntu_cis_2_3_2: true
ubuntu_cis_2_3_3: true
ubuntu_cis_2_3_4: true
ubuntu_cis_2_3_5: true
ubuntu_cis_2_3_6: true
ubuntu_cis_2_4: true
ubuntu_cis_3_1_1: false
ubuntu_cis_3_1_2: false
ubuntu_cis_3_2_1: true
ubuntu_cis_3_2_2: true
ubuntu_cis_3_3_1: true
ubuntu_cis_3_3_2: true
ubuntu_cis_3_3_3: true
ubuntu_cis_3_3_4: true
ubuntu_cis_3_3_5: true
ubuntu_cis_3_3_6: true
ubuntu_cis_3_3_7: true
ubuntu_cis_3_3_8: true
ubuntu_cis_3_3_9: false
ubuntu_cis_3_4_1: false
ubuntu_cis_3_4_2: false
ubuntu_cis_3_4_3: false
ubuntu_cis_3_4_4: false
ubuntu_cis_3_5_1_1: false
ubuntu_cis_3_5_1_2: false
ubuntu_cis_3_5_1_3: false
ubuntu_cis_3_5_1_4: false
ubuntu_cis_3_5_1_5: false
ubuntu_cis_3_5_1_6: false
ubuntu_cis_3_5_1_7: false
ubuntu_cis_3_5_2_1: false
ubuntu_cis_3_5_2_2: false
ubuntu_cis_3_5_2_3: false
ubuntu_cis_3_5_2_4: false
ubuntu_cis_3_5_2_5: false
ubuntu_cis_3_5_2_6: false
ubuntu_cis_3_5_2_7: false
ubuntu_cis_3_5_2_8: false
ubuntu_cis_3_5_2_9: false
ubuntu_cis_3_5_2_10: false
ubuntu_cis_3_5_3_1_1: false
ubuntu_cis_3_5_3_1_2: false
ubuntu_cis_3_5_3_1_3: false
ubuntu_cis_3_5_3_2_1: false
ubuntu_cis_3_5_3_2_2: false
ubuntu_cis_3_5_3_2_3: false
ubuntu_cis_3_5_3_2_4: false
ubuntu_cis_3_5_3_3_1: false
ubuntu_cis_3_5_3_3_2: false
ubuntu_cis_3_5_3_3_3: false
ubuntu_cis_3_5_3_3_4: false
ubuntu_cis_4_1_1_1: false
ubuntu_cis_4_1_1_2: false
ubuntu_cis_4_1_1_3: false
ubuntu_cis_4_1_1_4: false
ubuntu_cis_4_1_2_1: false
ubuntu_cis_4_1_2_2: false
ubuntu_cis_4_1_2_3: false
ubuntu_cis_4_1_3: true
ubuntu_cis_4_1_4: true
ubuntu_cis_4_1_5: true
ubuntu_cis_4_1_6: true
ubuntu_cis_4_1_7: true
ubuntu_cis_4_1_8: true
ubuntu_cis_4_1_9: true
ubuntu_cis_4_1_10: true
ubuntu_cis_4_1_11: true
ubuntu_cis_4_1_12: true
ubuntu_cis_4_1_13: true
ubuntu_cis_4_1_14: true
ubuntu_cis_4_1_15: false
ubuntu_cis_4_1_16: true
ubuntu_cis_4_1_17: true
ubuntu_cis_4_2_1_1: false
ubuntu_cis_4_2_1_2: false
ubuntu_cis_4_2_1_3: false
ubuntu_cis_4_2_1_4: false
ubuntu_cis_4_2_1_5: false
ubuntu_cis_4_2_1_6: false
ubuntu_cis_4_2_2_1: false
ubuntu_cis_4_2_2_2: false
ubuntu_cis_4_2_2_3: false
ubuntu_cis_4_2_3: false
ubuntu_cis_4_3: false
ubuntu_cis_4_4: false
ubuntu_cis_5_1_1: true
ubuntu_cis_5_1_2: true
ubuntu_cis_5_1_3: true
ubuntu_cis_5_1_4: true
ubuntu_cis_5_1_5: true
ubuntu_cis_5_1_6: true
ubuntu_cis_5_1_7: true
ubuntu_cis_5_1_8: true
ubuntu_cis_5_1_9: false
ubuntu_cis_5_2_1: true
ubuntu_cis_5_2_2: true
ubuntu_cis_5_2_3: false
ubuntu_cis_5_2_4: false
ubuntu_cis_5_2_5: true
ubuntu_cis_5_2_6: true
ubuntu_cis_5_2_7: true
ubuntu_cis_5_2_8: true
ubuntu_cis_5_2_9: true
ubuntu_cis_5_2_10: true
ubuntu_cis_5_2_11: true
ubuntu_cis_5_2_12: false
ubuntu_cis_5_2_13: false
ubuntu_cis_5_2_14: false
ubuntu_cis_5_2_15: false
ubuntu_cis_5_2_16: false
ubuntu_cis_5_2_17: false
ubuntu_cis_5_2_18: false
ubuntu_cis_5_2_19: false
ubuntu_cis_5_2_20: false
ubuntu_cis_5_2_21: false
ubuntu_cis_5_2_22: false
ubuntu_cis_5_3_1: true
ubuntu_cis_5_3_2: true
ubuntu_cis_5_3_3: true
ubuntu_cis_5_3_4: true
ubuntu_cis_5_4_1_1: false
ubuntu_cis_5_4_1_2: true
ubuntu_cis_5_4_1_3: true
ubuntu_cis_5_4_1_4: true
ubuntu_cis_5_4_1_5: false
ubuntu_cis_5_4_2: false
ubuntu_cis_5_4_3: true
ubuntu_cis_5_4_4: true
ubuntu_cis_5_4_5: false
ubuntu_cis_5_5: false
ubuntu_cis_5_6: true
ubuntu_cis_6_1_1: true
ubuntu_cis_6_1_2: true
ubuntu_cis_6_1_3: true
ubuntu_cis_6_1_4: true
ubuntu_cis_6_1_5: true
ubuntu_cis_6_1_6: true
ubuntu_cis_6_1_7: true
ubuntu_cis_6_1_8: true
ubuntu_cis_6_1_9: true
ubuntu_cis_6_1_10: true
ubuntu_cis_6_1_11: true
ubuntu_cis_6_1_12: true
ubuntu_cis_6_1_13: false
ubuntu_cis_6_1_14: false
ubuntu_cis_6_2_1: true
ubuntu_cis_6_2_2: true
ubuntu_cis_6_2_3: false
ubuntu_cis_6_2_4: false
ubuntu_cis_6_2_5: true
ubuntu_cis_6_2_6: true
ubuntu_cis_6_2_7: true
ubuntu_cis_6_2_8: true
ubuntu_cis_6_2_9: true
ubuntu_cis_6_2_10: true
ubuntu_cis_6_2_11: true
ubuntu_cis_6_2_12: true
ubuntu_cis_6_2_13: true
ubuntu_cis_6_2_14: true
ubuntu_cis_6_2_15: true
ubuntu_cis_6_2_16: true
ubuntu_cis_6_2_17: false

# # Keppel
# ubuntu_keppel_7_5_6: true
# ubuntu_keppel_8_2_3: true
# ubuntu_keppel_10_1_1: true
# ubuntu_keppel_10_1_2: true
# ubuntu_keppel_10_1_3: true
# ubuntu_keppel_13_21: true
# ubuntu_keppel_13_38: true
