---
- name: 4.2.3
  block:
    - name: 4.2.3 Ensure permissions on all logfiles are configured
      shell: find /var/log -type f -perm /g=wx -perm /o=rwx
      register: ubuntu_cis_4_2_3_out

    - name: 4.2.3 Ensure permissions on all logfiles are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_4_2_3"
        ubuntu_cis_rule_expected_values:
          - ""
        ubuntu_cis_rule_output: "{{ ubuntu_cis_4_2_3_out }}"
  ignore_errors: true
  when: ubuntu_cis_4_2_3 | bool

# - name: 4.3
#   block:
#     - name: 4.3 Ensure logrotate is configured

# - name: 4.4
#   block:
#     - name: 4.4 Ensure logrotate assigns appropriate permissions