---

# - name: 1.1.2
#   block:
#     - name: 1.1.2 Ensure /tmp is configured

- name: 1.1.3
  block:
    - name: 1.1.3 Ensure nodev option set on /tmp partition
      shell: mount | grep /tmp | grep nodev | cat
      register: ubuntu_cis_1_1_3_out      

    - name: 1.1.3 Ensure nodev option set on /tmp partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_1_3"
        ubuntu_cis_rule_expected_values:
          - "nodev"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_1_3_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_1_3 | bool

- name: 1.1.4
  block:
    - name: 1.1.4 Ensure nosuid option set on /tmp partition
      shell: mount | grep /tmp | grep nosuid | cat
      register: ubuntu_cis_1_1_4_out

    - name: 1.1.4 Ensure nosuid option set on /tmp partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_1_4"
        ubuntu_cis_rule_expected_values:
          - "nosuid"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_1_4_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_1_4 | bool

- name: 1.1.5
  block:
    - name: 1.1.5 Ensure noexec option set on /tmp partition
      shell: mount | grep /tmp | grep noexec | cat
      register: ubuntu_cis_1_1_5_out

    - name: 1.1.5 Ensure noexec option set on /tmp partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_1_5"
        ubuntu_cis_rule_expected_values:
          - "noexec"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_1_5_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_1_5 | bool

# - name: 1.1.6
#   block:
#     - name: 1.1.6 Ensure /dev/shm is configured

- name: 1.1.7
  block:
    - name: 1.1.7 Ensure nodev option set on /dev/shm partition
      shell: mount | grep /dev/shm | grep nodev | cat
      register: ubuntu_cis_1_1_7_out

    - name: 1.1.7 Ensure nodev option set on /dev/shm partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_1_7"
        ubuntu_cis_rule_expected_values:
          - "nodev"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_1_7_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_1_7 | bool

- name: 1.1.12
  block:
    - name: 1.1.12 Ensure nosuid option set on /dev/shm partition
      shell: mount | grep /dev/shm | grep nosuid | cat
      register: ubuntu_cis_1_1_12_out

    - name: 1.1.12 Ensure nosuid option set on /dev/shm partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_1_12"
        ubuntu_cis_rule_expected_values:
          - "nosuid"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_1_12_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_1_12 | bool

- name: 1.1.13
  block:
    - name: 1.1.13 Ensure noexec option set on /dev/shm partition
      shell: mount | grep /dev/shm | grep noexec | cat
      register: ubuntu_cis_1_1_13_out

    - name: 1.1.13 Ensure noexec option set on /dev/shm partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_1_13"
        ubuntu_cis_rule_expected_values:
          - "noexec"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_1_13_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_1_13 | bool

# - name: 1.1.14
#   block:
#     - name: 1.1.14 Ensure seperate partitions exist for /var  

# - name: 1.1.11
#   block:
#     - name: 1.1.11 Ensure seperate partitions exist for /var/tmp

- name: 1.1.12
  block:
    - name: 1.1.12 Ensure nodev option set on /var/tmp partition
      shell: mount | grep /var/tmp | grep nodev | cat
      register: ubuntu_cis_1_1_12_out

    - name: 1.1.12 Ensure nodev option set on /var/tmp partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_1_12"
        ubuntu_cis_rule_expected_values:
          - "nodev"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_1_12_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_1_12 | bool

- name: 1.1.13
  block:
    - name: 1.1.13 Ensure nosuid option set on /var/tmp partition
      shell: mount | grep /var/tmp | grep nosuid | cat
      register: ubuntu_cis_1_1_13_out

    - name: 1.1.13 Ensure nosuid option set on /var/tmp partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_1_13"
        ubuntu_cis_rule_expected_values:
          - "nosuid"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_1_13_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_1_13 | bool

- name: 1.1.14
  block:
    - name: 1.1.14 Ensure noexec option set on /var/tmp partition
      shell: mount | grep /var/tmp | grep noexec | cat
      register: ubuntu_cis_1_1_14_out

    - name: 1.1.14 Ensure noexec option set on /var/tmp partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_1_14"
        ubuntu_cis_rule_expected_values:
          - "noexec"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_1_14_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_1_14 | bool

# - name: 1.1.15
#   block:
#     - name: 1.1.15 Ensure seperate partitions exist for /var/log

# - name: 1.1.16
#   block:
#     - name: 1.1.16 Ensure seperate partitions exist for /var/log/audit

# - name: 1.1.17
#   block:
#     - name: 1.1.17 Ensure seperate partitions exist for /home

- name: 1.1.18
  block:
    - name: 1.1.18 Ensure nodev option set on /home partition
      shell: mount | grep /home | grep nodev | cat
      register: ubuntu_cis_1_1_18_out

    - name: 1.1.18 Ensure nodev option set on /home partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_1_18"
        ubuntu_cis_rule_expected_values:
          - "noexec"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_1_18_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_1_18 | bool


# - name: 1.1.19
#   block:
#     - name: 1.1.19 Ensure nodev option set on removable media partitions

# - name: 1.1.20
#   block:
#     - name: 1.1.20 Ensure nosuid option set on removable media partitions

# - name: 1.1.21
#   block:
#     - name: 1.1.21 Ensure noexec option set on removable media partitions

- name: 1.1.22
  block:
    - name: 1.1.22 Ensure sticky bit is set on all world-writable directories
      shell: >-
        df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null
      register: ubuntu_cis_1_1_22_out

    - name: 1.1.22 Ensure sticky bit is set on all world-writable directories | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_1_22"
        ubuntu_cis_rule_expected_values:
          - ""
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_1_22_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_1_22 | bool

- name: 1.1.23
  block:
    - name: 1.1.23 Disable Automounting
      shell: systemctl is-enabled autofs
      register: ubuntu_cis_1_1_23_out      

    - name: 1.1.23 Disable Automounting | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_1_23"
        ubuntu_cis_rule_expected_values:
         - - disabled
           - Failed to get unit file state
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_1_23_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_1_23 | bool

# - name: 1.1.24
#   block:
#     - name: 1.1.24 Disable USB Storage