---
- name: 5.1.1
  block:
    - name: 5.1.1 Ensure cron daemon is enabled
      shell: systemctl is-enabled crond
      register: ubuntu_cis_5_1_1_out

    - name: 5.1.1 Ensure cron daemon is enabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_5_1_1"
        ubuntu_cis_rule_expected_values:
          - "enabled"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_5_1_1_out }}"
  ignore_errors: true
  when: ubuntu_cis_5_1_1 | bool

- name: 5.1.2
  block:
    - name: 5.1.2 Ensure permissions on /etc/crontab are configured
      shell: stat /etc/crontab -c "%a %U %G"
      register: ubuntu_cis_5_1_2_out

    - name: 5.1.2 Ensure permissions on /etc/crontab are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_5_1_2"
        ubuntu_cis_rule_expected_values:
          - "600 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_5_1_2_out }}"
  ignore_errors: true
  when: ubuntu_cis_5_1_2 | bool

- name: 5.1.3
  block:
    - name: 5.1.3 Ensure permissions on /etc/cron.hourly are configured
      shell: stat /etc/cron.hourly -c "%a %U %G"
      register: ubuntu_cis_5_1_3_out

    - name: 5.1.3 Ensure permissions on /etc/cron.hourly are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_5_1_3"
        ubuntu_cis_rule_expected_values:
          - "700 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_5_1_3_out }}"
  ignore_errors: true
  when: ubuntu_cis_5_1_3 | bool

- name: 5.1.4
  block:
    - name: 5.1.4 Ensure permissions on /etc/cron.daily are configured
      shell: stat /etc/cron.daily -c "%a %U %G"
      register: ubuntu_cis_5_1_4_out

    - name: 5.1.4 Ensure permissions on /etc/cron.daily are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_5_1_4"
        ubuntu_cis_rule_expected_values:
          - "700 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_5_1_4_out }}"
  ignore_errors: true
  when: ubuntu_cis_5_1_4 | bool

- name: 5.1.5
  block:
    - name: 5.1.5 Ensure permissions on /etc/cron.weekly are configured
      shell: stat /etc/cron.weekly -c "%a %U %G"
      register: ubuntu_cis_5_1_5_out

    - name: 5.1.5 Ensure permissions on /etc/cron.weekly are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_5_1_5"
        ubuntu_cis_rule_expected_values:
          - "700 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_5_1_5_out }}"
  ignore_errors: true
  when: ubuntu_cis_5_1_5 | bool

- name: 5.1.6
  block:
    - name: 5.1.6 Ensure permissions on /etc/cron.monthly are configured
      shell: stat /etc/cron.monthly -c "%a %U %G"
      register: ubuntu_cis_5_1_6_out

    - name: 5.1.6 Ensure permissions on /etc/cron.monthly are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_5_1_6"
        ubuntu_cis_rule_expected_values:
          - "700 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_5_1_6_out }}"
  ignore_errors: true
  when: ubuntu_cis_5_1_6 | bool

- name: 5.1.7
  block:
    - name: 5.1.7 Ensure permissions on /etc/cron.d are configured
      shell: stat /etc/cron.d -c "%a %U %G"
      register: ubuntu_cis_5_1_7_out

    - name: 5.1.7 Ensure permissions on /etc/cron.d are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_5_1_7"
        ubuntu_cis_rule_expected_values:
          - "700 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_5_1_7_out }}"
  ignore_errors: true
  when: ubuntu_cis_5_1_7 | bool

- name: 5.1.8
  block:
    - name: 5.1.8 Ensure cron is restricted to authorized users
      shell: "{{ item }}"
      loop:
        - stat /etc/cron.deny
        - stat /etc/at.deny
        - stat /etc/cron.allow -c "%a %U %G"
        - stat /etc/at.allow -c "%a %U %G"
      register: ubuntu_cis_5_1_8_out

    - name: 5.1.8 Ensure at/cron is restricted to authorized users | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_5_1_8"
        ubuntu_cis_rule_expected_values:
          - "stat: cannot stat ‘/etc/cron.deny’: No such file or directory"
          - "stat: cannot stat ‘/etc/at.deny’: No such file or directory"
          - "600 root root"
          - "600 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_5_1_8_out }}"
  ignore_errors: true
  when: ubuntu_cis_5_1_8 | bool

- name: 5.1.9
  block:
    - name: 5.1.9 Ensure at is restricted to authorized users