---
- name: 1.8.1.1
  block:
    - name: 1.8.1.1 Ensure message of the day is configured properly
      shell: cat /etc/motd
      register: ubuntu_cis_1_8_1_1_out

    - name: 1.8.1.1 Ensure message of the day is configured properly | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_8_1_1"
        ubuntu_cis_rule_expected_values:
          - "{{ ubuntu_cis_1_8_1_1_expected_value }}"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_8_1_1_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_8_1_1 | bool

- name: 1.8.1.2
  block:
    - name: 1.8.1.2 Ensure local login warning banner is configured properly
      shell: cat /etc/issue
      register: ubuntu_cis_1_8_1_2_out

    - name: 1.8.1.2 Ensure local login warning banner is configured properly | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_8_1_2"
        ubuntu_cis_rule_expected_values:
          - "{{ ubuntu_cis_1_8_1_2_expected_value }}"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_8_1_2_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_8_1_2 | bool

- name: 1.8.1.3
  block:
    - name: 1.8.1.3 Ensure remote login warning banner is configured properly
      shell: cat /etc/issue.net
      register: ubuntu_cis_1_8_1_3_out

    - name: 1.8.1.3 Ensure remote login warning banner is configured properly | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_8_1_3"
        ubuntu_cis_rule_expected_values:
          - "{{ ubuntu_cis_1_8_1_3_expected_value }}"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_8_1_3_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_8_1_3 | bool

- name: 1.8.1.4
  block:
    - name: 1.8.1.4 Ensure permissions on /etc/motd are configured
      shell: stat /etc/motd -c "%a %U %G"
      register: ubuntu_cis_1_8_1_4_out

    - name: 1.8.1.4 Ensure permissions on /etc/motd are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_8_1_4"
        ubuntu_cis_rule_expected_values:
          - "644 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_8_1_4_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_8_1_4 | bool

- name: 1.8.1.5
  block:
    - name: 1.8.1.5 Ensure permissions on /etc/issue are configured
      shell: stat /etc/issue -c "%a %U %G"
      register: ubuntu_cis_1_8_1_5_out

    - name: 1.8.1.5 Ensure permissions on /etc/issue are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_8_1_5"
        ubuntu_cis_rule_expected_values:
          - "644 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_8_1_5_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_8_1_5 | bool

- name: 1.8.1.6
  block:
    - name: 1.8.1.6 Ensure permissions on /etc/issue.net are configured
      shell: stat /etc/issue.net -c "%a %U %G"
      register: ubuntu_cis_1_8_1_6_out

    - name: 1.8.1.6 Ensure permissions on /etc/issue.net are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_8_1_6"
        ubuntu_cis_rule_expected_values:
          - "644 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_8_1_6_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_8_1_6 | bool

# - name: 1.9
#   block:
#     - name: 1.9 Ensure updates, patches, and additional security software are installed
  
- name: 1.10
  block:
    - name: 1.10 Ensure GDM login banner is configured
      shell: cat /etc/dconf/profile/gdm
      register: ubuntu_cis_1_10_out

    - name: 1.10 Ensure GDM login banner is configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_10"
        ubuntu_cis_rule_expected_values:
          - "{{ ubuntu_cis_1_10_expected_value }}"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_10_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_10 | bool

