---
# run command "grep restrict..." twice to accommodate flags -4 and -6 (ipv4 and ipv6)
- name: 2.2.1.1
  block:
    - name: Ensure time synchronization is in use
      shell: "{{ item }}"
      loop:
        - rpm -q ntp
        - rpm -q chrony
      register: ubuntu_cis_2_2_1_1_out

    - name: Ensure time synchronization is in use | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_2_2_1_1"
        ubuntu_cis_rule_expected_values:
          - "ntp"
          - "chrony"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_2_2_1_1_out }}"
  ignore_errors: true
  when: ubuntu_cis_2_2_1_1 | bool

# - name: 2.2.1.2
#   block:
#     - name: 2.2.1.2 Ensure systemd-timesyncd is configured

- name: 2.2.1.3
  block:
    - name: 2.2.1.3 Ensure chrony is configured
      shell: "{{ item }}"
      loop:
        - grep "server" /etc/chrony.conf | grep -v ^#
        - grep "^OPTIONS" /etc/sysconfig/chronyd
      register: ubuntu_cis_2_2_1_3_out

    - name: 2.2.1.3 Ensure chrony is configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_2_2_1_3"
        ubuntu_cis_rule_expected_values:
          - "server {{ ubuntu_cis_2_2_1_3_server_expected_value }}"
          - 'OPTIONS="-u chrony"'
        ubuntu_cis_rule_output: "{{ ubuntu_cis_2_2_1_3_out }}"
  ignore_errors: true
  when: ubuntu_cis_2_2_1_3 | bool

# - name: 2.2.1.4
#   block:
#     - name: 2.2.1.4 Ensure ntp is configured