---
- name: 3.4.1.1
  block:
    - name: 3.4.1.1 Ensure a Firewall package is installed

- name: 3.4.2.1
  block:
    - name: 3.4.2.1 Ensure firewalld service is enabled and running

- name: 3.4.2.2
  block:
    - name: 3.4.2.2 Ensure iptables is not enabled

- name: 3.4.2.3
  block:
    - name: 3.4.2.3 Ensure nftables is not enabled

- name: 3.4.2.4
  block:
    - name: 3.4.2.4 Ensure default zone is set

- name: 3.4.2.5
  block:
    - name: 3.4.2.5 Ensure network interfaces are assigned to appropriate zone 

- name: 3.4.2.6
  block:
    - name: 3.4.2.6 Ensure unnecessary services and ports are not accepted 

- name: 3.4.3.1
  block:
    - name: 3.4.3.1 Ensure iptables are flushed

- name: 3.4.3.2
  block:
    - name: 3.4.3.2 Ensure a table exists

- name: 3.4.3.3
  block:
    - name: 3.4.3.3 Ensure base chains exist

- name: 3.4.3.4
  block:
    - name: 3.4.3.4 Ensure loopback traffic is configured

- name: 3.4.3.5
  block:
    - name: 3.4.3.5 Ensure outbound and established connections are configured

- name: 3.4.3.6
  block:
    - name: 3.4.3.6 Ensure default deny firewall policy

- name: 3.4.3.7
  block:
    - name: 3.4.3.7 Ensure nftables service is enabled

- name: 3.4.3.8
  block:
    - name: 3.4.3.8 Ensure nftables rules are permanent

- name: 3.4.4.1.1
  block:
    - name: 3.4.4.1.1 Ensure default deny firewall policy

- name: 3.4.4.1.2
  block:
    - name: 3.4.4.1.2 Ensure loopback traffic is configured

- name: 3.4.4.1.3
  block:
    - name: 3.4.4.1.3 Ensure outbound and established connections are configured

- name: 3.4.4.1.4
  block:
    - name: 3.4.4.1.4 Ensure firewall rules exist for all open ports

- name: 3.4.4.2.1
  block:
    - name: 3.4.4.2.1 Ensure IPv6 default deny firewall policy

- name: 3.4.4.2.2
  block:
    - name: 3.4.4.2.2 Ensure IPv6 loopback traffic is configured

- name: 3.4.4.2.3
  block:
    - name: 3.4.4.2.3 Ensure IPv6 outbound and established connections are configured

- name: 3.4.4.2.4
  block:
    - name: 3.4.4.2.4 Ensure IPv6 firewall rules exist for all open ports