---
# - name: 1.3.1
#   block:
#     - name: 1.3.1 Ensure sudo is installed

# - name: 1.3.2
#   block:
#     - name: 1.3.2 Ensure sudo commands use pty

# - name: 1.3.3
#   block:
#     - name: 1.3.3 Ensure sudo log file exists


