---
- name: 6.1.1
  block:
    - name: 6.1.1 Audit system file permissions
      shell: rpm -Va --nomtime --nosize --nomd5 --nolinkto
      register: ubuntu_cis_6_1_1_out

    - name: 6.1.1 Audit system file permissions | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_6_1_1"
        ubuntu_cis_rule_expected_values:
          - ""
        ubuntu_cis_rule_output: "{{ ubuntu_cis_6_1_1_out }}"
  ignore_errors: true
  when: ubuntu_cis_6_1_1 | bool

- name: 6.1.2
  block:
    - name: 6.1.2 Ensure permissions on /etc/passwd are configured
      shell: stat /etc/passwd -c "%a %U %G"
      register: ubuntu_cis_6_1_2_out

    - name: 6.1.2 Ensure permissions on /etc/passwd are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_6_1_2"
        ubuntu_cis_rule_expected_values:
          - "644 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_6_1_2_out }}"
  ignore_errors: true
  when: ubuntu_cis_6_1_2 | bool

- name: 6.1.3
  block:
    - name: 6.1.3 Ensure permissions on /etc/gshadow- are configured
      shell: stat /etc/gshadow- -c "%a %U %G"
      register: ubuntu_cis_6_1_3_out

    - name: 6.1.8 Ensure permissions on /etc/gshadow- are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_6_1_3"
        ubuntu_cis_rule_expected_values:
          - "0 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_6_1_3_out }}"
  ignore_errors: true
  when: ubuntu_cis_6_1_3 | bool

- name: 6.1.4
  block:
    - name: 6.1.4 Ensure permissions on /etc/shadow are configured
      shell: stat /etc/shadow -c "%a %U %G"
      register: ubuntu_cis_6_1_4_out

    - name: 6.1.4 Ensure permissions on /etc/shadow are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_6_1_4"
        ubuntu_cis_rule_expected_values:
          - "0 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_6_1_4_out }}"
  ignore_errors: true
  when: ubuntu_cis_6_1_4 | bool

- name: 6.1.5
  block:
    - name: 6.1.5 Ensure permissions on /etc/group are configured
      shell: stat /etc/group -c "%a %U %G"
      register: ubuntu_cis_6_1_5_out

    - name: 6.1.5 Ensure permissions on /etc/group are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_6_1_5"
        ubuntu_cis_rule_expected_values:
          - "644 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_6_1_5_out }}"
  ignore_errors: true
  when: ubuntu_cis_6_1_5 | bool

- name: 6.1.6
  block:
    - name: 6.1.6 Ensure permissions on /etc/passwd- are configured
      shell: stat /etc/passwd- -c "%a %U %G"
      register: ubuntu_cis_6_1_6_out

    - name: 6.1.6 Ensure permissions on /etc/passwd- are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_6_1_6"
        ubuntu_cis_rule_expected_values:
          - "644 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_6_1_6_out }}"
  ignore_errors: true
  when: ubuntu_cis_6_1_6 | bool

- name: 6.1.7
  block:
    - name: 6.1.7 Ensure permissions on /etc/shadow- are configured
      shell: stat /etc/shadow- -c "%a %U %G"
      register: ubuntu_cis_6_1_7_out

    - name: 6.1.7 Ensure permissions on /etc/passwd- are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_6_1_7"
        ubuntu_cis_rule_expected_values:
          - "0 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_6_1_7_out }}"
  ignore_errors: true
  when: ubuntu_cis_6_1_7 | bool

- name: 6.1.8
  block:
    - name: 6.1.8 Ensure permissions on /etc/group- are configured
      shell: stat /etc/group- -c "%a %U %G"
      register: ubuntu_cis_6_1_8_out

    - name: 6.1.8 Ensure permissions on /etc/group- are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_6_1_8"
        ubuntu_cis_rule_expected_values:
          - "644 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_6_1_8_out }}"
  ignore_errors: true
  when: ubuntu_cis_6_1_8 | bool

- name: 6.1.9
  block:
    - name: 6.1.9 Ensure permissions on /etc/gshadow are configured
      shell: stat /etc/gshadow -c "%a %U %G"
      register: ubuntu_cis_6_1_9_out

    - name: 6.1.9 Ensure permissions on /etc/gshadow are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_6_1_9"
        ubuntu_cis_rule_expected_values:
          - "0 root root"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_6_1_9_out }}"
  ignore_errors: true
  when: ubuntu_cis_6_1_9 | bool

- name: 6.1.10
  block:
    - name: 6.1.10 Ensure no world writable files exist
      shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -0002
      register: ubuntu_cis_6_1_10_out

    - name: 6.1.10 Ensure no world writable files exist | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_6_1_10"
        ubuntu_cis_rule_expected_values:
          - ""
        ubuntu_cis_rule_output: "{{ ubuntu_cis_6_1_10_out }}"
  ignore_errors: true
  when: ubuntu_cis_6_1_10 | bool

- name: 6.1.11
  block:
    - name: 6.1.11 Ensure no unowned files or directories exist
      shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser
      register: ubuntu_cis_6_1_11_out

    - name: 6.1.11 Ensure no unowned files or directories exist | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_6_1_11"
        ubuntu_cis_rule_expected_values:
          - ""
        ubuntu_cis_rule_output: "{{ ubuntu_cis_6_1_11_out }}"
  ignore_errors: true
  when: ubuntu_cis_6_1_11 | bool

- name: 6.1.12
  block:
    - name: 6.1.12 Ensure no ungrouped files or directories exist
      shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nogroup
      register: ubuntu_cis_6_1_12_out

    - name: 6.1.12 Ensure no ungrouped files or directories exist | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_6_1_12"
        ubuntu_cis_rule_expected_values:
          - ""
        ubuntu_cis_rule_output: "{{ ubuntu_cis_6_1_12_out }}"
  ignore_errors: true
  when: ubuntu_cis_6_1_12 | bool

- name: 6.1.13
  block:
    - name: 6.1.13 Audit SUID executables

- name: 6.1.14
  block:
    - name: 6.1.14 Audit SGID executables    