---
# - name: 5.4.1.1
#   block:
#     - name: 5.4.1.1 Ensure password expiration is 365 days or less

- name: 5.4.1.2
  block:
    - name: 5.4.1.2 Ensure minimum days between password changes is configured
      shell: grep PASS_MIN_DAYS /etc/login.defs | grep -v ^#
      register: ubuntu_cis_5_4_1_2_out

    - name: 5.4.1.3 Ensure minimum days between password changes is 7 or more | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_5_4_1_2"
        ubuntu_cis_rule_expected_values:
          - "PASS_MIN_DAYS 7"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_5_4_1_2_out }}"
  ignore_errors: true
  when: ubuntu_cis_5_4_1_2 | bool

- name: 5.4.1.3
  block:
    - name: 5.4.1.3 Ensure password expiration warning days is 7 or more
      shell: grep PASS_WARN_AGE /etc/login.defs | grep -v ^#
      register: ubuntu_cis_5_4_1_3_out

    - name: 5.4.1.3 Ensure password expiration warning days is 7 or more | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_5_4_1_3"
        ubuntu_cis_rule_expected_values:
          - "PASS_WARN_AGE 7"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_5_4_1_3_out }}"
  ignore_errors: true
  when: ubuntu_cis_5_4_1_3 | bool

- name: 5.4.1.4
  block:
    - name: 5.4.1.4 Ensure inactive password lock is 30 days or less
      shell: useradd -D | grep INACTIVE
      register: ubuntu_cis_5_4_1_4_out

    - name: 5.4.1.4 Ensure inactive password lock is 30 days or less | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_5_4_1_4"
        ubuntu_cis_rule_expected_values:
          - "INACTIVE=30"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_5_4_1_4_out }}"
  ignore_errors: true
  when: ubuntu_cis_5_4_1_4 | bool

# - name: 5.4.1.5
#   block:
#     - name: 5.4.1.5 Ensure all users last password change date is in the past 
