---
# - name: 1.3.1
#   block:
#     - name: 1.3.1 Ensure sudo is installed

# - name: 1.3.2
#   block:
#     - name: 1.3.2 Ensure sudo commands use pty

# - name: 1.3.3
#   block:
#     - name: 1.3.3 Ensure sudo log file exists

- name: 1.4.1
  block:
    - name: 1.4.1 Ensure AIDE is installed
      shell: rpm -q aide
      register: ubuntu_cis_1_4_1_out      

    - name: 1.4.1 Ensure AIDE is installed | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_4_1"
        ubuntu_cis_rule_expected_values:
          - "aide"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_4_1_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_4_1 | bool

- name: 1.4.2
  block:
    - name: 1.4.2 Ensure filesystem integrity is regularly checked
      shell: grep -rh aide /etc/cron.* /etc/crontab
      register: ubuntu_cis_1_4_2_out

    - name: 1.4.2 Ensure filesystem integrity is regularly checked | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        ubuntu_cis_rule_key: "cis_1_4_2"
        ubuntu_cis_rule_expected_values:
          - "/usr/sbin/aide --check"
        ubuntu_cis_rule_output: "{{ ubuntu_cis_1_4_2_out }}"
  ignore_errors: true
  when: ubuntu_cis_1_4_2 | bool


